---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: user-versoview-ns-dev
data:
  app_secret: dmVyc292aWV3LXNlY3JldC1rZXk=
  mail_username: dmVyc292aWV3LnVzZXJAYWxwaGFpdC51cw==
  mail_password: QWxwaEA3MDQ=